name: Stanley-lua/Debug
description: Debug utilities for Lua.
version: 0.1
author: 
  - email: wolf2789@gmail.com
    name: Dawid Bugajski
autoload:
  - type: global
    name: debug
    path: Debug.lua
